FROM python:3.11.7
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install --no-install-recommends -y sox libsox-fmt-all curl wget gcc git git-lfs build-essential libaio-dev libsndfile1 ssh ffmpeg && \
    apt-get clean && apt-get -y autoremove

WORKDIR /app
COPY requirements_cpu.txt .
RUN python -m pip install -r requirements_cpu.txt \
    && python -m pip cache purge

RUN python -m unidic download
RUN mkdir -p /app/src /app/tts_models /app/speaker_profiles

COPY .env /app/.env
COPY src /app/src
ENV USE_CPU=1

WORKDIR /app/src
EXPOSE 8004
CMD ["python", "main.py"]
